### ISSUE TITLE
NTLM proxy problems in Jboss Studio developer

### ISSUE THREAD

**Issue by timlansbergen** [jbdevstudio/jbdevstudio-product#496]
Hi all,

It looks like Jboss developer studio doesn't support the NTLM proxy. I checked the logs the developer studio and the following exception is thrown:
!ENTRY org.eclipse.epp.logging.aeri.ide 2 17 2018-06-18 11:27:57.492
!MESSAGE Server ‘org.jboss.tools’ failed with exception: Proxy Authentication Required. ; version: 2.0.7.v20170906-1327
!STACK 0
org.apache.http.client.HttpResponseException: Proxy Authentication Required
	at org.eclipse.epp.internal.logging.aeri.ide.server.mars.HttpResponses$ProgressMonitorResponseHandler.handleResponse(HttpResponses.java:66)
	at org.eclipse.epp.internal.logging.aeri.ide.server.mars.HttpResponses$ProgressMonitorResponseStringHandler.handleResponse(HttpResponses.java:88)
	at org.eclipse.epp.internal.logging.aeri.ide.server.mars.HttpResponses$ProgressMonitorResponseStringHandler.handleResponse(HttpResponses.java:1)
	at org.apache.http.client.fluent.Response.handleResponse(Response.java:90)
	at org.eclipse.epp.internal.logging.aeri.ide.server.mars.HttpResponses.getContentWithProgress(HttpResponses.java:51)
	at org.eclipse.epp.internal.logging.aeri.ide.server.mars.IO.refreshConfiguration(IO.java:65)
	at org.eclipse.epp.internal.logging.aeri.ide.server.mars.ServerConnection.startUp(ServerConnection.java:124)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
	at java.lang.Thread.run(Unknown Source)

We have the same issue with the standalone version of Maven, however this issue can be solved by putting the "wagon-http=lightweight-2.2.jar" into the lib/ext folder of Maven. Please see this link for more details about this workaround: https://codepen.io/ugbandula/post/how-to-configure-maven-to-work-with-ntlm-proxies
Do you also have such a solution for the Jboss Developer Studio?

Kind regards,

Tim

**Comment by sbouchet** [comment]
Hi @timlansbergen, 
we removed the AERI dependency from Developer Studio in the latest version. Can you try again with a newer version? 
Also, please use the JIRA to open issues: https://issues.redhat.com/browse/JBDS

Thanks
